Client/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Client import views

urlpatterns = [
    path('Client/Job/Applied/List/', views.Applied_Job_View, name='applied_job_list'),
    path('Client/Job/List/', views.JobView, name='job_list'),
    path('Client/Job/add/', views.JobCreateView, name='job_add'),
    path('Client/Job/<int:pk>/update', views.JobUpdateView, name='job_change'),
    path('Client/Job/delete/<int:pk>/', views.JobDelete.as_view(), name='job_delete'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('client/profile/', views.Clientprofile, name='client_profile'),
    path('client/registration/', views.ClientCreateView, name='client_add'),
    path('client/profile/update/<int:pk>/', views.ClientUserUpdateView, name='client_change'),
    path('client/profile/create/', views.ClientProfileCreateView, name='client_profile_create'),
    path('client/profile/<int:pk>/update', views.ClientProfileUpdateView,
         name='client_profile_update'),

    path('client/change/password/', views.ChangePasswordView.as_view(), name='client_change_password'),

]

EasyWork/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('client/', include('Client.urls')),
    path('superadmin/', include('superadmin.urls')),
    path('', views.base, name='base'),
    # path('home/', views.home, name='home'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Client/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from accounts.models import Country, City
from django.contrib.auth import get_user_model
User = get_user_model()


class Job(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    country = models.ForeignKey(Country, verbose_name="Category", on_delete=models.SET_NULL, null=True)
    city = models.ManyToManyField(City, verbose_name="Sub Category", )
    Title = models.CharField(max_length=100)
    content = models.TextField()
    applied_username = models.ForeignKey(User, null=True,blank=True,on_delete=models.CASCADE,
                                         related_name='applied_username')
    is_apply = models.BooleanField('Apply',null=True,blank=True)
    is_published = models.BooleanField('Published',default=False)
    image = models.ImageField(default='default.jpg', upload_to='job_pics',blank=True,null=True)
    location = models.CharField(max_length=100,null=True,blank=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.username)

    def save(self, *args, **kwargs):
        super(Job, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

Client/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

from Client.models import Job
from accounts.models import Profile, City

User = get_user_model()


class ClientProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone_number','address','image')


class ClientSignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username','email','image','password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        user.is_customer = True
        user.save()
        return user


class ClientSignUpUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username','first_name','last_name','email',]


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ('Title','country', 'city','content','location','image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()
        self.fields["city"].widget = forms.widgets.CheckboxSelectMultiple()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

Client/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model, login
from django.views.generic import DeleteView
from django.contrib.auth.decorators import login_required
from accounts.filters import JobFilter
from .models import Job
from accounts.models import Profile, City
from .forms import ClientSignUpForm,ClientSignUpUpdateForm,ClientProfileUpdateForm,JobForm
from django.contrib.auth.views import (
     PasswordChangeView as BasePasswordChangeView,
)
User = get_user_model()


def Clientprofile(request):
    return render(request,'Client/client_profile.html')


def ClientCreateView(request):
    if request.method == 'POST':
        u_form = ClientSignUpForm(request.POST or None, request.FILES or None)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been created! You are waiting for approval')
            return redirect('login')
    else:
        u_form = ClientSignUpForm()

    context = {
            'u_form': u_form,

        }
    return render(request, 'Client/client_reg.html', context)


# Super Admin profile Update

def ClientUserUpdateView(request, pk):
    person = get_object_or_404(User, pk=pk)
    form = ClientSignUpUpdateForm(instance=person)
    if request.method == 'POST':
        form = ClientSignUpUpdateForm(request.POST,request.FILES, instance=person)
        if form.is_valid():
            form.save()
            return redirect('client_profile')
    return render(request, 'Client/client_basic_update.html', {'form': form})


# Client profile Update

def ClientProfileCreateView(request):
    form = ClientProfileUpdateForm()
    if request.method == 'POST':
        form = ClientProfileUpdateForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('client_profile')
    return render(request, 'client/client_profile_create.html', {'form': form})


# Client profile Update

def ClientProfileUpdateView(request, pk):
    person = get_object_or_404(Profile, pk=pk)
    form = ClientProfileUpdateForm(instance=person)
    if request.method == 'POST':
        form = ClientProfileUpdateForm(request.POST,request.FILES, instance=person)
        if form.is_valid():
            form.save()
            return redirect('client_profile')
    return render(request, 'client/client_profile_create.html', {'form': form})


class ChangePasswordView(BasePasswordChangeView):
    template_name = 'Client/change_password.html'

    def form_valid(self, form):
        # Change the password
        user = form.save()

        # Re-authentication
        login(self.request, user)

        messages.success(self.request, f'Your password was changed.')

        return redirect('login')


def JobView(request):
    job = Job.objects.all()
    MyFilter = JobFilter(request.GET, queryset=job)
    job = MyFilter.qs
    context = {
        'job': job,
        'MyFilter': MyFilter,
    }
    return render(request, 'Client/job_list.html', context)


# Job Post Create

def JobCreateView(request):
    form = JobForm()
    if request.method == 'POST':
        form = JobForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.instance.username = request.user
            form.save()
            return redirect('job_list')
    return render(request, 'Client/home.html', {'form': form})


# JOb Post Update
@login_required()
def JobUpdateView(request, pk):
    person = get_object_or_404(Job, pk=pk)
    form = JobForm(instance=person)
    if request.method == 'POST':
        form = JobForm(request.POST,request.FILES, instance=person)
        if form.is_valid():
            form.save()
            return redirect('job_list')
    return render(request, 'Client/home.html', {'form': form})


class JobDelete(DeleteView):
    model = Job
    template_name = 'Client/job_delete.html'
    success_url = 'http://127.0.0.1:8000/client/Client/Job/List/'


# Worker Service AJAX
def load_cities(request):
    country_id = request.GET.get('country_id')
    cities = City.objects.filter(country_id=country_id).all()
    return render(request, 'Client/city_dropdown_list_options.html', {'cities': cities})


def Applied_Job_View(request):
    job = Job.objects.all().filter(is_apply=True)
    MyFilter = JobFilter(request.GET, queryset=job)
    job = MyFilter.qs
    context = {
        'job': job,
        'MyFilter': MyFilter,
    }
    return render(request, 'Client/applied_job.html', context)

Client/templates/Client/applied_job.html
{% extends 'index1.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<h3 class="btn btn-primary">Applied Job Post</h3>
<br><br><br><br><br><br><br><br><br><br><br>
<form method="get">
    {{ MyFilter.form }}
    <button class="btn btn-primary" type="submit">Search</button>
</form>
<div class="site-section">
        <div class="container">
            <div class="row">
                {% for job in job %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="course-1-item">
                            <figure class="thumnail">
                            <a><img src="{{ job.image.url }}" alt="Image" class="img-fluid" style="height: 350px; width:350px;"></a>
                            <div class="alert alert-info" role="alert">
                              Job Category : {{ job.country }}
                            </div>
                            <div class="alert alert-success" role="alert">
                              Job Sub Category :<br>
                                {% for job in job.city.all %}
                                         {{ job.name }}<br>
                                {% endfor%}</h3>
                            </div>
                            <div class="alert alert-success" role="alert">
                              Job Applied UserName : {{ job.applied_username }}
                            </div>
                            <div class="alert alert-danger" role="alert">
                              Job Applied User Phone Number  : {{ job.applied_username.profile.phone_number }}
                            </div>
                            </figure>
                        </div>
                    </div>
                {% endfor%}
            </div>
        </div>
</div>
{% endblock content %}

Client/templates/Client/change_password.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Client Change Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Update Password</button>
                </div>

            </form>
        </div>
{% endblock content %}

Client/templates/Client/city_dropdown_list_options.html
{% load static %}
<style>
        #id_city {
            width: 100%;
        }
    </style>
<!--<option value="">---------</option>-->
{% for city in cities %}
<!--<input type="checkbox" value="{{ city.pk }}" name="{{ city.name }}">-->

        <input type="checkbox" value="{{city.id}}" name="city">{{ city.name }}<br>

<!--<option value="{{ city.pk }}">{{ city.name }}</option>-->
{% endfor %}

Client/templates/Client/client_basic_update.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>
<body>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Client Profile Basic Information</h1>
    {{ form|crispy }}

    <input  class="btn btn-primary" type="submit" value="Submit">

     <a  class="btn btn-primary" href="{% url 'client_profile' %}">Back Profile</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</body>
</html>

{% endblock content %}

Client/templates/Client/client_profile.html
{% extends 'index1.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
    <div class="content-section">
        {% if user.profile.user %}

        {% else %}
         <div class="form-group">
             <h1>******please fill up user profile</h1>
            <a  class="btn btn-primary" href="{% url 'client_profile_create'  %}">ADD Profile</a>
        </div>
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img width="150px" height="200px"" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">UserName : {{ user.username }}</h2>
          <h3 class="text-secondary">Email : {{ user.email }}</h3>
          <h3 class="text-secondary">Phone Number : {{ user.profile.phone_number }}</h3>
          <h3 class="text-secondary">First Name : {{ user.first_name }}</h3>
          <h3 class="text-secondary">Last Name : {{ user.last_name }}</h3>
           <h3 class="text-secondary">Full NAME : {{ user.first_name }} {{ user.last_name }} </h3>
                    <br><br><br><br><br>
            <div class="form-group">

                <a  class="btn btn-primary" href="{% url 'client_change' user.pk %}">1.Change Profile</a>
                {% if user.profile.user == user %}
                <a  class="btn btn-primary" href="{% url 'client_profile_update' user.profile.pk %}">2.Change Profile</a>
                {% endif %}
                <a  class="btn btn-primary" href="{% url 'client_change_password' %}">Change Password</a>
            </div>

          </div>
      </div>
    </div>
{% endblock content %}

Client/templates/Client/client_profile_create.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>
<body>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Client Profile Basic Information</h1>
    {{ form|crispy }}

    <input  class="btn btn-primary" type="submit" value="Submit">

     <a  class="btn btn-primary" href="{% url 'client_profile' %}">Back Profile</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</body>
</html>

{% endblock content %}

Client/templates/Client/client_reg.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>
<body>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Client Basic Information</h1>
    {{ u_form|crispy }}

    <input  class="btn btn-primary" type="submit" value="Submit">

    <a  class="btn btn-primary" href="{% url 'login' %}">Back Login</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</body>
</html>

{% endblock content %}

Client/templates/Client/home.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>
<body>

<form method="post" id="JobForm" data-cities-url="{% url 'ajax_load_cities' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Client Job Post Information</h1>
    {{ form.as_p }}


    <input  class="btn btn-primary" type="submit" value="Submit">

    <a  class="btn btn-primary" href="{% url 'profile' %}">Back Profile</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#JobForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });
    });
</script>

</body>
</html>

{% endblock content %}

Client/templates/Client/job_delete.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
<div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Delete Job ID ###{{ object.id}}</span>
            <hr>
          <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
               <h2 align="center"> Are you sure you want to delete <strong>{{ object.Title }}</strong> ?</h2>
            </div>
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Client/templates/Client/job_list.html
{% extends 'index1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br>
<form method="get">
    {{ MyFilter.form }}
    <button class="btn btn-primary" type="submit">Search</button>
</form>
<table class="table">
     <a  class="btn btn-primary" href="{% url 'job_add' %}">Add Job Post</a>
  <thead class="thead-light">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Image</th>
      <th scope="col">Category Name </th>
      <th scope="col">Sub Category Name </th>
      <th scope="col">Content </th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for job in job %}
   {% if job.username == user%}
    <tr>
      <th scope="row">{{ job.id}}</th>
      <td>{{ job.Title }}</td>
         <td>
        <img class="rounded-circle account-img" src="{{ job.image.url }}" style="height: 150px; width:150px;">
      </td>
      <td>{{ job.country }}</td>
      <td>
        {% for job in job.city.all %}
          {{ job.name }}<br>
        {% endfor%}
      </td>
      <td>{{ job.content }}</td>
      <td>
          <a href="{% url 'job_change' job.id %}" class="btn btn-primary"> Edit</a>
      </td>
      <td>
          <a href="{% url 'job_delete' job.id %}" class="btn btn-warning"> Delete</a>
      </td>
    </tr>

    {% endif %}
    {% endfor %}
  </tbody>
</table>
{% endblock content %}